pull_request_rules:
- actions:
    queue:
      name: default
      method: squash
      commit_message_template: |
        {{ title }} (#{{ number }})
        {{ body }}
  name: Automatically merge pull requests on approval
  conditions:
  - label=merge me
  - ! '#approved-reviews-by>=1'
  - ! '#changes-requested-reviews-by=0'
- actions:
    delete_head_branch: {}
  name: Delete head branch after merge
  conditions:
  - merged